//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageOpener.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hacker
    {
        public int ID { get; set; }
        public string Address { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string User { get; set; }
        public string Parola { get; set; }
    }
}
