//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageOpener.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public System.Guid ID { get; set; }
        public int UserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
    }
}
